name: my_lock
version: 0.1.0+1
publish_to: none

environment:
  sdk: '>=3.13.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^11.2.0
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/branding/mylock_launcher_standard-1.png"
  adaptive_icon_foreground: "assets/branding/mylock_launcher_standard-1.png"
  adaptive_icon_background: "#F4F2FF"
  adaptive_icon_foreground_inset: 0
  min_sdk_android: 21
